from typing import Any, TypedDict

from backend.app.config import Settings
from backend.app.llm.azure_gpt5 import AzureGpt5Service


class GraphState(TypedDict, total=False):
    run_id: str
    user_id: str
    goal: str
    target_url: str
    namespace: str | None
    scope: dict[str, Any]
    plan: dict[str, Any]
    log_marker: str
    final_report: str
    runtime: str


class ReadOnlyDemoGraph:
    """Minimal Phase 1 LangGraph wrapper for read-only diagnostic planning."""

    def __init__(self, *, settings: Settings, llm: AzureGpt5Service) -> None:
        self.settings = settings
        self.llm = llm
        self._compiled = self._compile_graph()

    async def ainvoke(self, state: GraphState) -> GraphState:
        if self._compiled is None:
            return await self._fallback_ainvoke(state)
        config = {"configurable": {"thread_id": state["run_id"]}}
        result = await self._compiled.ainvoke(state, config=config)
        result["runtime"] = "langgraph"
        return result

    def _compile_graph(self):
        if self.settings.langgraph_checkpointer == "disabled":
            return None
        try:
            from langgraph.checkpoint.memory import MemorySaver
            from langgraph.graph import END, START, StateGraph
        except Exception:
            return None

        graph = StateGraph(GraphState)
        graph.add_node("load_scope", self._load_scope)
        graph.add_node("plan", self._plan)
        graph.add_node("write_postgres_logs", self._write_postgres_logs)
        graph.add_node("final_report", self._final_report)
        graph.add_edge(START, "load_scope")
        graph.add_edge("load_scope", "plan")
        graph.add_edge("plan", "write_postgres_logs")
        graph.add_edge("write_postgres_logs", "final_report")
        graph.add_edge("final_report", END)
        checkpointer = MemorySaver() if self.settings.langgraph_checkpointer == "memory" else None
        return graph.compile(checkpointer=checkpointer)

    async def _fallback_ainvoke(self, state: GraphState) -> GraphState:
        state = await self._load_scope(state)
        state = await self._plan(state)
        state = await self._write_postgres_logs(state)
        state = await self._final_report(state)
        state["runtime"] = "sequential_fallback"
        return state

    async def _load_scope(self, state: GraphState) -> GraphState:
        return state | {
            "scope": {
                "workflow_type": "health_check_diagnostic",
                "allowed_tools": ["rest.get", "powershell.ps_http_get", "mcp.k8s_inspector"],
                "autonomy_mode": "observe_only",
            }
        }

    async def _plan(self, state: GraphState) -> GraphState:
        plan = await self.llm.diagnostic_plan(
            goal=state["goal"],
            target_url=state["target_url"],
            namespace=state.get("namespace"),
        )
        return state | {"plan": plan}

    async def _write_postgres_logs(self, state: GraphState) -> GraphState:
        return state | {"log_marker": "postgres_logging_delegated_to_workflow"}

    async def _final_report(self, state: GraphState) -> GraphState:
        plan = state.get("plan") or {}
        return state | {
            "final_report": str(
                plan.get(
                    "reasoning_summary",
                    "Read-only diagnostic plan generated by the Phase 1 graph.",
                )
            )
        }